language: go

notifications:
  email: false

go:
  - 1.5
  - tip

install:
  - cd deps/base64 && make

script:
  - cd $TRAVIS_BUILD_DIR/base64 && go test -timeout 1m -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)