language: go

notifications:
  email: false

go:
  - 1.7
  - tip

install:
  - cd c-deps/base64 && make

script:
  - cd $TRAVIS_BUILD_DIR/pkg && go test -timeout 1m -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)